In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
emdat = pd.read_csv('../data/emdat.csv')

In [4]:
emdat['Disaster Group'].value_counts()

Disaster Group
Natural    2331
Name: count, dtype: int64

In [5]:
us_emdat = emdat.loc[emdat['Country'] == 'United States of America']

In [6]:
us_emdat = us_emdat.reset_index(drop = True)

In [7]:
us_emdat = us_emdat.loc[us_emdat['Disaster Group'] == 'Natural']

In [8]:
us_emdat = us_emdat.drop(columns = {'DisNo.',
                         'Historic',
                         'Classification Key',
                         'External IDs',
                         'Event Name',
                         'ISO',
                         'Origin',
                         'Associated Types',
                         'OFDA/BHA Response',
                         'Appeal',
                         'Declaration',
                         "AID Contribution ('000 US$)",
                         'River Basin',
                         "Reconstruction Costs ('000 US$)",
                         "Reconstruction Costs, Adjusted ('000 US$)",
                         'Admin Units',
                         'Entry Date',
                         'Last Update'})

In [9]:
us_emdat.loc[12, 'Location']

'Anderson, Benton, Cheatham, Davidson, Henry, Hickman, Houston, Jackson, Knox, Lake, Obion, Perry, Pickett, Stewart districts (Tennessee ,)'

In [10]:
us_emdat['Disaster Type'].value_counts()

Disaster Type
Storm                  361
Flood                  116
Wildfire                78
Extreme temperature     16
Drought                 15
Earthquake              10
Epidemic                 3
Mass movement (wet)      3
Volcanic activity        1
Name: count, dtype: int64

In [11]:
us_emdat['Disaster Subtype'].value_counts()

Disaster Subtype
Tornado                             103
Riverine flood                       69
Blizzard/Winter storm                69
Tropical cyclone                     61
Forest fire                          46
Severe weather                       43
Storm (General)                      41
Lightning/Thunderstorms              32
Flood (General)                      29
Wildfire (General)                   22
Flash flood                          18
Drought                              15
Heat wave                            10
Ground movement                      10
Land fire (Brush, Bush, Pasture)     10
Hail                                  8
Cold wave                             3
Severe winter conditions              3
Viral disease                         2
Mudslide                              2
Derecho                               2
Infectious disease (General)          1
Extra-tropical storm                  1
Landslide (wet)                       1
Lava flow                             1
Sand/Dust storm                       1
Name: count, dtype: int64

In [12]:
us_emdat['Location'] = us_emdat['Location'].astype(str)

In [13]:
us_emdat.info()

<class 'pandas.core.frame.DataFrame'>
Index: 603 entries, 0 to 602
Data columns (total 28 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Disaster Group                       603 non-null    object
 1   Disaster Subgroup                    603 non-null    object
 2   Disaster Type                        603 non-null    object
 3   Disaster Subtype                     603 non-null    object
 4   Country                              603 non-null    object
 5   Subregion                            603 non-null    object
 6   Region                               603 non-null    object
 7   Location                             603 non-null    object
 8   Magnitude                            208 non-null    float64
 9   Magnitude Scale                      599 non-null    object
 10  Latitude                             61 non-null     float64
 11  Longitude                            61 non-null     float64
 12  Start Year                           603 non-null    int64
 13  Start Month                          603 non-null    float64
 14  Start Day                            570 non-null    float64
 15  End Year                             603 non-null    int64
 16  End Month                            600 non-null    float64
 17  End Day                              572 non-null    float64
 18  Total Deaths                         459 non-null    float64
 19  No. Injured                          183 non-null    float64
 20  No. Affected                         244 non-null    float64
 21  No. Homeless                         93 non-null     float64
 22  Total Affected                       375 non-null    float64
 23  Insured Damage ('000 US$)            243 non-null    float64
 24  Insured Damage, Adjusted ('000 US$)  243 non-null    float64
 25  Total Damage ('000 US$)              454 non-null    float64
 26  Total Damage, Adjusted ('000 US$)    449 non-null    float64
 27  CPI                                  592 non-null    float64
dtypes: float64(17), int64(2), object(9)
memory usage: 152.8+ KB

In [14]:
us_emdat

,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Country,Subregion,Region,Location,Magnitude,Magnitude Scale,Latitude,Longitude,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,No. Injured,No. Affected,No. Homeless,Total Affected,Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI
0,Natural,Meteorological,Storm,Tornado,United States of America,Northern America,Americas,"Crittenden, Daviess, Webster districts (Kentuc...",NaN,Kph,NaN,NaN,2000,1.0,2.0,2000,1.0,4.0,1.0,12.0,NaN,150.0,162.0,200500.0,354778.0,210000.0,371587.0,56.514291
1,Natural,Meteorological,Storm,Tornado,United States of America,Northern America,Americas,"Bullock, Montgomery districts (Alabama ,), Col...",249.0,Kph,NaN,NaN,2000,2.0,13.0,2000,2.0,14.0,22.0,100.0,900.0,NaN,1000.0,NaN,NaN,NaN,NaN,56.514291
2,Natural,Hydrological,Flood,Riverine flood,United States of America,Northern America,Americas,"Kentucky, Ohio ,s",55000.0,Km2,NaN,NaN,2000,2.0,18.0,2000,2.0,22.0,3.0,NaN,231.0,NaN,231.0,NaN,NaN,NaN,NaN,56.514291
3,Natural,Climatological,Wildfire,Forest fire,United States of America,Northern America,Americas,"Gainesville, Alachua areas (Alachua district, ...",113.0,Km2,NaN,NaN,2000,2.0,26.0,2000,2.0,26.0,NaN,NaN,600.0,NaN,600.0,NaN,NaN,NaN,NaN,56.514291
4,Natural,Meteorological,Storm,Tornado,United States of America,Northern America,Americas,"Fort Worth Texas city (Tarrant district, Texas...",NaN,Kph,NaN,NaN,2000,3.0,28.0,2000,3.0,28.0,5.0,NaN,3000.0,300.0,3300.0,NaN,NaN,450000.0,796259.0,56.514291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,Natural,Meteorological,Storm,Tornado,United States of America,Northern America,Americas,"Oklahoma, Iowa, Nebraska, Texas, Kansas, Misso...",NaN,Kph,NaN,NaN,2024,4.0,25.0,2024,5.0,8.0,4.0,NaN,558.0,597.0,1155.0,NaN,NaN,NaN,NaN,NaN
599,Natural,Meteorological,Storm,Severe weather,United States of America,Northern America,Americas,"Houston (Texas), Kansas, Oklahoma, Missouri, I...",160.0,Kph,NaN,NaN,2024,5.0,16.0,2024,5.0,22.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
600,Natural,Meteorological,Storm,Tornado,United States of America,Northern America,Americas,Greenfield (Iowa state),NaN,Kph,NaN,NaN,2024,5.0,22.0,2024,5.0,22.0,5.0,35.0,NaN,300.0,335.0,NaN,NaN,NaN,NaN,NaN
601,Natural,Meteorological,Storm,Severe weather,United States of America,Northern America,Americas,"Arkansas, Texas, eastern Oklahoma, Kentucky, A...",NaN,Kph,NaN,NaN,2024,5.0,23.0,2024,5.0,30.0,23.0,80.0,102.0,NaN,182.0,NaN,NaN,NaN,NaN,NaN
602,Natural,Climatological,Wildfire,Forest fire,United States of America,Northern America,Americas,"Otero and Lincoln Counties (New Mexico), Calif...",NaN,Km2,NaN,NaN,2024,6.0,19.0,2024,6.0,21.0,2.0,2.0,1500.0,NaN,1502.0,NaN,NaN,NaN,NaN,NaN

In [15]:
states = ['Alabama','Alaska', 'Arizona', 'Arkansas',
          'California', 'Colorado', 'Connecticut',
          'Delaware', 'Florida', 'Georgia', 'Hawaii',
          'Idaho', 'Illinois', 'Indiana', 'Iowa',
          'Kansas', 'Kentucky', 'Louisiana', 'Maine',
          'Maryland', 'Massachusetts', 'Michigan',
          'Minnesota', 'Mississippi', 'Missouri',
          'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
          'New Jersey', 'New Mexico', 'New York',
          'North Carolina', 'North Dakota', 'Ohio',
          'Oklahoma', 'Oregon', 'Pennsylvania',
          'Rhode Island', 'South Carolina', 'South Dakota',
          'Tennessee', 'Texas', 'Utah', 'Vermont',
          'Virginia', 'Washington', 'West Virginia',
          'Wisconsin', 'Wyoming','Washington D.C.']
state_set = set(states)

In [16]:
def extract_states(location):
    locations = [loc.strip() for loc in location.split(',')]
    found_states = [state for state in locations if state in state_set]
    return ', '.join(found_states)

#### code i may need later for below
.str.replace('province', '').str.replace('state','')
us_emdat['Location'] = us_emdat['Location'].str.replace('eastern','').str.replace('western','').str.replace('northern','').str.replace('southern','')
us_emdat['Location'] = us_emdat['Location'].str.replace(' s','').str.replace('Vernon','').str.replace('districts','').str.replace('district','')

In [18]:
us_emdat['Location'] = us_emdat['Location'].str.replace('(',', ').str.replace(')',',').str.replace('province', '').str.replace('state','')
us_emdat['Location'] = us_emdat['Location'].str.replace('eastern','').str.replace('western','').str.replace('northern','').str.replace('southern','')
us_emdat['Location'] = us_emdat['Location'].str.replace('Vernon','').str.replace('districts','').str.replace('district','')
us_emdat['Location'] = us_emdat['Location'].str.replace('Center andouth of ',',')

In [19]:
us_emdat['State'] = us_emdat['Location'].apply(extract_states)

In [20]:
us_emdat = us_emdat.reset_index(drop = True)

In [21]:
us_emdat.columns

Index(['Disaster Group', 'Disaster Subgroup', 'Disaster Type',
       'Disaster Subtype', 'Country', 'Subregion', 'Region', 'Location',
       'Magnitude', 'Magnitude Scale', 'Latitude', 'Longitude', 'Start Year',
       'Start Month', 'Start Day', 'End Year', 'End Month', 'End Day',
       'Total Deaths', 'No. Injured', 'No. Affected', 'No. Homeless',
       'Total Affected', 'Insured Damage ('000 US$)',
       'Insured Damage, Adjusted ('000 US$)', 'Total Damage ('000 US$)',
       'Total Damage, Adjusted ('000 US$)', 'CPI', 'State'],
      dtype='object')

In [22]:
us_emdat['State'] = us_emdat['State'].astype(str)  # Ensure 'State' is treated as a string
us_emdat = us_emdat.assign(State=us_emdat['State'].str.split(',')).explode('State')

In [23]:
us_emdat = us_emdat.reset_index(drop = True)
us_emdat

,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Country,Subregion,Region,Location,Magnitude,Magnitude Scale,Latitude,Longitude,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,No. Injured,No. Affected,No. Homeless,Total Affected,Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,State
0,Natural,Meteorological,Storm,Tornado,United States of America,Northern America,Americas,"Crittenden, Daviess, Webster , Kentucky ,,",NaN,Kph,NaN,NaN,2000,1.0,2.0,2000,1.0,4.0,1.0,12.0,NaN,150.0,162.0,200500.0,354778.0,210000.0,371587.0,56.514291,Kentucky
1,Natural,Meteorological,Storm,Tornado,United States of America,Northern America,Americas,"Bullock, Montgomery , Alabama ,,, Colquitt, G...",249.0,Kph,NaN,NaN,2000,2.0,13.0,2000,2.0,14.0,22.0,100.0,900.0,NaN,1000.0,NaN,NaN,NaN,NaN,56.514291,Alabama
2,Natural,Meteorological,Storm,Tornado,United States of America,Northern America,Americas,"Bullock, Montgomery , Alabama ,,, Colquitt, G...",249.0,Kph,NaN,NaN,2000,2.0,13.0,2000,2.0,14.0,22.0,100.0,900.0,NaN,1000.0,NaN,NaN,NaN,NaN,56.514291,Georgia
3,Natural,Meteorological,Storm,Tornado,United States of America,Northern America,Americas,"Bullock, Montgomery , Alabama ,,, Colquitt, G...",249.0,Kph,NaN,NaN,2000,2.0,13.0,2000,2.0,14.0,22.0,100.0,900.0,NaN,1000.0,NaN,NaN,NaN,NaN,56.514291,Washington
4,Natural,Meteorological,Storm,Tornado,United States of America,Northern America,Americas,"Bullock, Montgomery , Alabama ,,, Colquitt, G...",249.0,Kph,NaN,NaN,2000,2.0,13.0,2000,2.0,14.0,22.0,100.0,900.0,NaN,1000.0,NaN,NaN,NaN,NaN,56.514291,Arkansas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3399,Natural,Meteorological,Storm,Severe weather,United States of America,Northern America,Americas,"Arkansas, Texas, Oklahoma, Kentucky, Alabama,...",NaN,Kph,NaN,NaN,2024,5.0,23.0,2024,5.0,30.0,23.0,80.0,102.0,NaN,182.0,NaN,NaN,NaN,NaN,NaN,Kentucky
3400,Natural,Meteorological,Storm,Severe weather,United States of America,Northern America,Americas,"Arkansas, Texas, Oklahoma, Kentucky, Alabama,...",NaN,Kph,NaN,NaN,2024,5.0,23.0,2024,5.0,30.0,23.0,80.0,102.0,NaN,182.0,NaN,NaN,NaN,NaN,NaN,Alabama
3401,Natural,Meteorological,Storm,Severe weather,United States of America,Northern America,Americas,"Arkansas, Texas, Oklahoma, Kentucky, Alabama,...",NaN,Kph,NaN,NaN,2024,5.0,23.0,2024,5.0,30.0,23.0,80.0,102.0,NaN,182.0,NaN,NaN,NaN,NaN,NaN,Colorado
3402,Natural,Climatological,Wildfire,Forest fire,United States of America,Northern America,Americas,"Otero and Lincoln Counties , New Mexico,, Cali...",NaN,Km2,NaN,NaN,2024,6.0,19.0,2024,6.0,21.0,2.0,2.0,1500.0,NaN,1502.0,NaN,NaN,NaN,NaN,NaN,New Mexico
3403,Natural,Climatological,Wildfire,Forest fire,United States of America,Northern America,Americas,"Otero and Lincoln Counties , New Mexico,, Cali...",NaN,Km2,NaN,NaN,2024,6.0,19.0,2024,6.0,21.0,2.0,2.0,1500.0,NaN,1502.0,NaN,NaN,NaN,NaN,NaN,California

In [24]:
us_emdat['State'] = us_emdat['State'].str.replace(' ','')

In [25]:
us_emdat['State'].value_counts()

State
Texas             183
Missouri          139
Oklahoma          132
Illinois          114
Kansas            112
Mississippi       110
Alabama           103
Arkansas          100
Georgia            97
Ohio               97
Louisiana          96
Tennessee          96
NorthCarolina      95
Kentucky           94
California         94
Pennsylvania       90
Indiana            86
Iowa               86
NewYork            86
Virginia           85
Florida            81
Nebraska           80
NewJersey          71
SouthCarolina      70
Wisconsin          70
Minnesota          66
Colorado           64
Michigan           63
Maryland           62
SouthDakota        54
Massachusetts      51
NorthDakota        47
Washington         46
Connecticut        44
NewMexico          41
WestVirginia       40
NewHampshire       36
Maine              35
RhodeIsland        32
Wyoming            30
Vermont            29
Delaware           29
Arizona            27
Montana            26
Oregon             24
WashingtonD.C.     22
Nevada             21
Utah               12
Hawaii             11
Idaho              10
                   10
Alaska              5
Name: count, dtype: int64

In [26]:
us_emdat.to_csv('us_emdat.csv')

In [27]:
us_emdat = pd.read_csv('../data/us_emdat.csv')

In [28]:
us_emdat['State'].value_counts()

State
Texas              183
Missouri           139
Oklahoma           132
Illinois           114
Kansas             112
Mississippi        110
Alabama            103
Arkansas           100
Georgia             97
Ohio                97
Louisiana           96
Tennessee           96
North Carolina      95
Kentucky            94
California          94
Pennsylvania        90
Indiana             86
Iowa                86
New York            86
Virginia            85
Florida             81
Nebraska            80
New Jersey          71
Wisconsin           70
South Carolina      70
Minnesota           66
Colorado            64
Michigan            63
Maryland            62
South Dakota        54
Massachusetts       51
North Dakota        47
Washington          46
Connecticut         44
New Mexico          41
West Virginia       40
New Hampshire       36
Maine               35
Rhode Island        32
Wyoming             30
Vermont             29
Delaware            29
Arizona             27
Montana             26
Oregon              24
Washington D.C.     22
Nevada              21
Utah                12
Hawaii              11
Idaho               10
Alaska               5
Name: count, dtype: int64

In [29]:
us_emdat.groupby('Disaster Subtype')['State'].value_counts()

Disaster Subtype       State
Blizzard/Winter storm  New York         37
                       Pennsylvania     30
                       New Jersey       28
                       Virginia         25
                       Massachusetts    24
                                        ..
Wildfire (General)     Florida           1
                       Hawaii            1
                       Idaho             1
                       Kansas            1
                       Nebraska          1
Name: count, Length: 619, dtype: int64

In [30]:
stuffs = us_emdat[['State','Disaster Subtype']]

In [31]:
stuffs = stuffs.value_counts().reset_index()

In [32]:
stuffs

             State       Disaster Subtype  count
0            Texas                Tornado     41
1          Alabama                Tornado     39
2         Missouri                Tornado     38
3      Mississippi                Tornado     37
4         New York  Blizzard/Winter storm     37
..             ...                    ...    ...
614       Nebraska     Wildfire (General)      1
615       Nebraska          Viral disease      1
616     California   Extra-tropical storm      1
617        Montana         Riverine flood      1
618  New Hampshire         Severe weather      1

[619 rows x 3 columns]

In [33]:
stuffs.columns = ['state','disaster_subtype','amount']
stuffs

             state       disaster_subtype  amount
0            Texas                Tornado      41
1          Alabama                Tornado      39
2         Missouri                Tornado      38
3      Mississippi                Tornado      37
4         New York  Blizzard/Winter storm      37
..             ...                    ...     ...
614       Nebraska     Wildfire (General)       1
615       Nebraska          Viral disease       1
616     California   Extra-tropical storm       1
617        Montana         Riverine flood       1
618  New Hampshire         Severe weather       1

[619 rows x 3 columns]

In [34]:
disasters = pd.crosstab(us_emdat['Disaster Subtype'],us_emdat['State'])

In [35]:
disasters

State,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,Florida,Georgia,Hawaii,Idaho,Illinois,Indiana,Iowa,Kansas,Kentucky,Louisiana,Maine,Maryland,Massachusetts,Michigan,Minnesota,Mississippi,Missouri,Montana,Nebraska,Nevada,New Hampshire,New Jersey,New Mexico,New York,North Carolina,North Dakota,Ohio,Oklahoma,Oregon,Pennsylvania,Rhode Island,South Carolina,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,Washington D.C.,West Virginia,Wisconsin,Wyoming
Disaster Subtype,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Blizzard/Winter storm,12,0,1,11,4,12,18,9,6,18,0,3,14,10,12,16,13,13,15,21,24,13,12,11,19,4,15,1,16,28,9,37,24,11,14,16,6,30,14,16,13,17,17,1,13,25,6,12,10,14,6
Cold wave,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,2,1,1,2,0,1,1,1,2,0,0,0,1,2,0,2,1,0,1,1,0,3,1,1,0,0,1,0,1,1,0,1,0,0,0
Derecho,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
Drought,1,0,4,0,5,1,0,0,1,2,0,1,4,3,3,5,0,3,0,1,0,3,3,0,4,2,4,3,0,0,2,0,0,4,3,3,2,0,0,1,4,0,4,2,0,0,2,0,0,3,1
Extra-tropical storm,0,0,0,1,1,1,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0
Flash flood,1,0,2,3,2,2,0,0,1,1,0,1,1,1,1,1,1,1,0,0,0,0,1,0,2,0,0,2,0,0,1,1,0,0,2,3,0,1,0,1,0,1,4,3,0,0,1,0,0,1,0
Flood (General),3,0,2,5,2,2,2,0,2,1,3,0,4,3,1,2,4,5,0,1,1,0,1,3,6,0,2,0,1,3,1,1,2,1,1,3,1,4,0,1,0,3,9,0,1,1,2,1,1,0,1
Forest fire,0,2,7,0,26,6,0,0,6,2,0,2,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,3,0,0,4,0,0,1,0,2,4,0,0,0,1,2,6,1,0,1,4,0,1,0,2
Ground movement,0,0,0,0,7,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
Hail,1,0,0,3,0,2,0,1,0,1,0,0,4,5,4,4,3,0,0,1,0,2,1,0,6,1,2,0,0,0,1,1,1,0,3,5,0,2,0,1,0,3,5,0,0,1,3,0,1,2,0
Heat wave,1,0,3,0,2,0,0,0,1,0,0,1,2,1,3,2,1,2,1,0,0,1,2,1,2,0,2,1,0,0,1,2,1,1,3,2,1,0,0,0,2,0,3,1,0,1,2,1,0,2,0
"Land fire (Brush, Bush, Pasture)",0,0,1,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
Landslide (wet),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
Lava flow,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Lightning/Thunderstorms,4,0,1,8,0,8,4,1,1,4,0,1,14,10,8,13,5,8,3,4,4,8,9,9,14,4,9,2,3,4,5,6,4,6,11,11,0,9,3,3,8,5,16,1,3,6,4,1,3,7,8
Mudslide,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Riverine flood,3,2,2,7,10,4,2,2,2,3,3,0,11,5,8,8,9,1,3,2,5,6,8,4,11,1,3,5,3,9,1,3,3,6,12,14,3,4,2,0,3,8,15,1,2,5,6,0,1,9,0
Severe weather,14,0,1,12,6,8,2,2,10,6,0,0,12,10,8,12,11,13,2,3,2,4,5,13,15,3,12,1,1,3,7,3,6,7,8,15,1,2,1,9,8,11,20,0,0,3,0,1,4,7,3
Severe winter conditions,0,0,0,2,0,0,0,0,0,0,0,0,1,0,1,1,1,2,2,0,1,1,1,1,0,0,0,0,1,0,0,2,0,0,1,1,0,0,0,0,0,0,2,0,2,0,0,0,0,1,0
Storm (General),10,0,0,9,5,6,7,4,8,10,0,0,11,9,10,13,9,10,3,6,7,9,7,11,14,3,11,1,5,8,1,13,10,3,9,15,3,14,6,8,4,10,21,0,3,11,4,0,8,8,5
Tornado,39,0,1,35,0,8,2,4,12,30,0,0,30,25,26,32,32,17,2,10,3,10,12,37,38,5,18,0,3,3,5,5,17,7,23,34,0,12,2,15,11,31,41,0,2,12,4,0,8,12,4
Tropical cyclone,11,0,0,3,1,1,5,5,29,16,1,0,1,1,1,0,1,19,2,10,2,1,0,17,2,0,0,0,2,10,0,8,25,0,4,2,0,9,2,14,0,4,13,0,2,16,3,4,3,0,0
Viral disease,2,0,0,0,1,0,1,0,1,2,1,0,2,1,0,1,1,1,1,1,2,2,1,2,2,0,1,0,0,1,1,1,1,0,1,0,0,0,1,0,0,1,3,1,0,2,0,1,0,2,0
Wildfire (General),0,0,2,0,11,3,0,0,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,2,1,0,0,0,2,0,0,0,0,3,2,0,0,0,0,0,2,1,0,0,2,0,0,0,0

In [36]:
population = pd.read_csv('../data/population_years.csv')

In [37]:
population.columns

Index(['State', 'Resident Population 2020 Census',
       'Percent Change 2020 Census', 'Resident Population 2010 Census',
       'Percent Change 2010 Census', 'Resident Population 2000 Census',
       'Percent Change 2000 Census', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26'],
      dtype='object')

In [38]:
population.drop( columns = ['Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26'])

,State,Resident Population 2020 Census,Percent Change 2020 Census,Resident Population 2010 Census,Percent Change 2010 Census,Resident Population 2000 Census,Percent Change 2000 Census
0,Alabama,"5,024,279",5.1,"4,779,736",7.5,"4,447,100",10.1
1,Alaska,"733,391",3.3,"710,231",13.3,"626,932",14.0
2,Arizona,"7,151,502",11.9,"6,392,017",24.6,"5,130,632",40.0
3,Arkansas,"3,011,524",3.3,"2,915,918",9.1,"2,673,400",13.7
4,California,"39,538,223",6.1,"37,253,956",10.0,"33,871,648",13.8
5,Colorado,"5,773,714",14.8,"5,029,196",16.9,"4,301,261",30.6
6,Connecticut,"3,605,944",0.9,"3,574,097",4.9,"3,405,565",3.6
7,Delaware,"989,948",10.2,"897,934",14.6,"783,600",17.6
8,District of Columbia,"689,545",14.6,"601,723",5.2,"572,059",-5.7
9,Florida,"21,538,187",14.6,"18,801,310",17.6,"15,982,378",23.5
10,Georgia,"10,711,908",10.6,"9,687,653",18.3,"8,186,453",26.4
11,Hawaii,"1,455,271",7.0,"1,360,301",12.3,"1,211,537",9.3
12,Idaho,"1,839,106",17.3,"1,567,582",21.1,"1,293,953",28.5
13,Illinois,"12,812,508",-0.1,"12,830,632",3.3,"12,419,293",8.6
14,Indiana,"6,785,528",4.7,"6,483,802",6.6,"6,080,485",9.7
15,Iowa,"3,190,369",4.7,"3,046,355",4.1,"2,926,324",5.4
16,Kansas,"2,937,880",3.0,"2,853,118",6.1,"2,688,418",8.5
17,Kentucky,"4,505,836",3.8,"4,339,367",7.4,"4,041,769",9.7
18,Louisiana,"4,657,757",2.7,"4,533,372",1.4,"4,468,976",5.9
19,Maine,"1,362,359",2.6,"1,328,361",4.2,"1,274,923",3.8
20,Maryland,"6,177,224",7.0,"5,773,552",9.0,"5,296,486",10.8
21,Massachusetts,"7,029,917",7.4,"6,547,629",3.1,"6,349,097",5.5
22,Michigan,"10,077,331",2.0,"9,883,640",-0.6,"9,938,444",6.9
23,Minnesota,"5,706,494",7.6,"5,303,925",7.8,"4,919,479",12.4
24,Mississippi,"2,961,279",-0.2,"2,967,297",4.3,"2,844,658",10.5
25,Missouri,"6,154,913",2.8,"5,988,927",7.0,"5,595,211",9.3
26,Montana,"1,084,225",9.6,"989,415",9.7,"902,195",12.9
27,Nebraska,"1,961,504",7.4,"1,826,341",6.7,"1,711,263",8.4
28,Nevada,"3,104,614",15.0,"2,700,551",35.1,"1,998,257",66.3
29,New Hampshire,"1,377,529",4.6,"1,316,470",6.5,"1,235,786",11.4
30,New Jersey,"9,288,994",5.7,"8,791,894",4.5,"8,414,350",8.9
31,New Mexico,"2,117,522",2.8,"2,059,179",13.2,"1,819,046",20.1
32,New York,"20,201,249",4.2,"19,378,102",2.1,"18,976,457",5.5
33,North Carolina,"10,439,388",9.5,"9,535,483",18.5,"8,049,313",21.4
34,North Dakota,"779,094",15.8,"672,591",4.7,"642,200",0.5
35,Ohio,"11,799,448",2.3,"11,536,504",1.6,"11,353,140",4.7
36,Oklahoma,"3,959,353",5.5,"3,751,351",8.7,"3,450,654",9.7
37,Oregon,"4,237,256",10.6,"3,831,074",12.0,"3,421,399",20.4
38,Pennsylvania,"13,002,700",2.4,"12,702,379",3.4,"12,281,054",3.4
39,Rhode Island,"1,097,379",4.3,"1,052,567",0.4,"1,048,319",4.5
40,South Carolina,"5,118,425",10.7,"4,625,364",15.3,"4,012,012",15.1
41,South Dakota,"886,667",8.9,"814,180",7.9,"754,844",8.5
42,Tennessee,"6,910,840",8.9,"6,346,105",11.5,"5,689,283",16.7
43,Texas,"29,145,505",15.9,"25,145,561",20.6,"20,851,820",22.8
44,Utah,"3,271,616",18.4,"2,763,885",23.8,"2,233,169",29.6
45,Vermont,"643,077",2.8,"625,741",2.8,"608,827",8.2
46,Virginia,"8,631,393",7.9,"8,001,024",13.0,"7,078,515",14.4
47,Washington,"7,705,281",14.6,"6,724,540",14.1,"5,894,121",21.1
48,West Virginia,"1,793,716",-3.2,"1,852,994",2.5,"1,808,344",0.8
49,Wisconsin,"5,893,718",3.6,"5,686,986",6.0,"5,363,675",9.6
50,Wyoming,"576,851",2.3,"563,626",14.1,"493,782",8.9
51,United States1,"331,449,281",7.4,"308,745,538",9.7,"281,421,906",13.2

In [39]:
us_emdat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3404 entries, 0 to 3403
Data columns (total 31 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Disaster Group                       3404 non-null   object
 1   Disaster Subgroup                    3404 non-null   object
 2   Disaster Type                        3404 non-null   object
 3   Disaster Subtype                     3404 non-null   object
 4   Country                              3404 non-null   object
 5   Subregion                            3404 non-null   object
 6   Region                               3404 non-null   object
 7   Location                             3403 non-null   object
 8   Magnitude                            1065 non-null   float64
 9   Magnitude Scale                      3400 non-null   object
 10  Latitude                             210 non-null    float64
 11  Longitude                            210 non-null    float64
 12  start_date                           3404 non-null   object
 13  Start Year                           3404 non-null   int64
 14  Start Month                          3404 non-null   int64
 15  Start Day                            3404 non-null   int64
 16  end_date                             3404 non-null   object
 17  End Year                             3404 non-null   int64
 18  End Month                            3385 non-null   float64
 19  End Day                              3404 non-null   int64
 20  Total Deaths                         2950 non-null   float64
 21  No. Injured                          1160 non-null   float64
 22  No. Affected                         1072 non-null   float64
 23  No. Homeless                         278 non-null    float64
 24  Total Affected                       1829 non-null   float64
 25  Insured Damage ('000 US$)            1918 non-null   float64
 26  Insured Damage, Adjusted ('000 US$)  1918 non-null   float64
 27  Total Damage ('000 US$)              2788 non-null   float64
 28  Total Damage, Adjusted ('000 US$)    2761 non-null   float64
 29  CPI                                  3347 non-null   float64
 30  State                                3394 non-null   object
dtypes: float64(14), int64(5), object(12)
memory usage: 824.5+ KB